# This is a basic workflow to help you get started with Actions

name: updateREADME

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    # 定时任务每分钟执行一次 分别代表分(0-59)、时(0-23)、天(1-31)、月(1-12)、周(0-6)
    - cron:  '0 3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  start:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 输出IP
      - name: IP
        run: sudo curl ifconfig.me
      # 设置服务器时区为东八区 
      - name: Set time zone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # 安装依赖
      - name: npm install
        run: npm install
      # 执行脚本
      - name: 执行脚本
        run: |
          node ./算法/autoGenerate/bilibili/index.js
          node ./算法/autoGenerate/juejin/index.js
          node ./算法/autoGenerate/generateREADME.js 
      # git 提交文件
      - name: Commit files
        run: |
          git config --local user.email "yufei0453@qq.com"
          git config --local user.name "Action"
          git add .
          git commit -m "`date '+%Y-%m-%d %H:%M:%S'` 更新README.md" #动态提交信息
      # Runs a set of commands using the runners shell
      # 推送到github仓库
      - name: Push changes
        run: git push origin main
          
